CREATE TABLE good_category(
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(255),
    description    varchar
);

CREATE TABLE good(
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(255),
    description    varchar,
    price          NUMERIC,
    category       bigint,
    FOREIGN KEY (category) REFERENCES good (id)
);

CREATE TABLE payment_type(
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          varchar(255),
    description    varchar
);

CREATE TABLE delivery_type(
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          varchar(255),
    description    varchar
);

CREATE TABLE user_info(
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(255),
    email          varchar
);

CREATE TABLE recipient(
    id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name           varchar,
    last_name            varchar,
    middle_name          varchar,
    address             varchar,
    zip_code             varchar,
    phone               varchar,
    user_info           bigint,
    FOREIGN KEY (user_info) REFERENCES user_info (id)
);

CREATE TABLE transaction(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       date,
    updated_at       date,
    status          varchar(255),
    amount          NUMERIC,
    provider_data   jsonb
);

CREATE TABLE checkout(
    id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_info           bigint,
    transaction         bigint,
    payment_type        bigint,
    delivery_type       bigint,
    basket              jsonb,
    recipient           jsonb,
    FOREIGN KEY (user_info) REFERENCES user_info (id),
    FOREIGN KEY (transaction) REFERENCES transaction (id),
    FOREIGN KEY (payment_type) REFERENCES payment_type (id),
    FOREIGN KEY (delivery_type) REFERENCES delivery_type (id)
);

CREATE TABLE refresh_token(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        varchar(255),
    refresh_token    varchar,
    revoked         boolean,
    date_created     date
);